package com.google.a.a;

import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.regex.Pattern;

public final class bl
{
  private static final bb a = bb.a('\n').a();
  private static final bb b = bb.a(f.a).a();
  private static final f c = f.a("‘’");
  private static final f d = f.a("“”");
  private static final Map<String, Character> e;
  private static final f f;
  private static final bm g;
  private static final Pattern h;
  private static final Pattern i;
  private static final Set<Character.UnicodeBlock> j;
  private static final char[] k;
  private static final char[] l;
  private static final bp m;
  private static final bp n;
  private static final bp o = 5.a();

  static
  {
    HashMap localHashMap = new HashMap(252);
    localHashMap.put("&nbsp", Character.valueOf(' '));
    localHashMap.put("&iexcl", Character.valueOf('¡'));
    localHashMap.put("&cent", Character.valueOf('¢'));
    localHashMap.put("&pound", Character.valueOf('£'));
    localHashMap.put("&curren", Character.valueOf('¤'));
    localHashMap.put("&yen", Character.valueOf('¥'));
    localHashMap.put("&brvbar", Character.valueOf('¦'));
    localHashMap.put("&sect", Character.valueOf('§'));
    localHashMap.put("&uml", Character.valueOf('¨'));
    localHashMap.put("&copy", Character.valueOf('©'));
    localHashMap.put("&ordf", Character.valueOf('ª'));
    localHashMap.put("&laquo", Character.valueOf('«'));
    localHashMap.put("&not", Character.valueOf('¬'));
    localHashMap.put("&shy", Character.valueOf('­'));
    localHashMap.put("&reg", Character.valueOf('®'));
    localHashMap.put("&macr", Character.valueOf('¯'));
    localHashMap.put("&deg", Character.valueOf('°'));
    localHashMap.put("&plusmn", Character.valueOf('±'));
    localHashMap.put("&sup2", Character.valueOf('²'));
    localHashMap.put("&sup3", Character.valueOf('³'));
    localHashMap.put("&acute", Character.valueOf('´'));
    localHashMap.put("&micro", Character.valueOf('µ'));
    localHashMap.put("&para", Character.valueOf('¶'));
    localHashMap.put("&middot", Character.valueOf('·'));
    localHashMap.put("&cedil", Character.valueOf('¸'));
    localHashMap.put("&sup1", Character.valueOf('¹'));
    localHashMap.put("&ordm", Character.valueOf('º'));
    localHashMap.put("&raquo", Character.valueOf('»'));
    localHashMap.put("&frac14", Character.valueOf('¼'));
    localHashMap.put("&frac12", Character.valueOf('½'));
    localHashMap.put("&frac34", Character.valueOf('¾'));
    localHashMap.put("&iquest", Character.valueOf('¿'));
    localHashMap.put("&Agrave", Character.valueOf('À'));
    localHashMap.put("&Aacute", Character.valueOf('Á'));
    localHashMap.put("&Acirc", Character.valueOf('Â'));
    localHashMap.put("&Atilde", Character.valueOf('Ã'));
    localHashMap.put("&Auml", Character.valueOf('Ä'));
    localHashMap.put("&Aring", Character.valueOf('Å'));
    localHashMap.put("&AElig", Character.valueOf('Æ'));
    localHashMap.put("&Ccedil", Character.valueOf('Ç'));
    localHashMap.put("&Egrave", Character.valueOf('È'));
    localHashMap.put("&Eacute", Character.valueOf('É'));
    localHashMap.put("&Ecirc", Character.valueOf('Ê'));
    localHashMap.put("&Euml", Character.valueOf('Ë'));
    localHashMap.put("&Igrave", Character.valueOf('Ì'));
    localHashMap.put("&Iacute", Character.valueOf('Í'));
    localHashMap.put("&Icirc", Character.valueOf('Î'));
    localHashMap.put("&Iuml", Character.valueOf('Ï'));
    localHashMap.put("&ETH", Character.valueOf('Ð'));
    localHashMap.put("&Ntilde", Character.valueOf('Ñ'));
    localHashMap.put("&Ograve", Character.valueOf('Ò'));
    localHashMap.put("&Oacute", Character.valueOf('Ó'));
    localHashMap.put("&Ocirc", Character.valueOf('Ô'));
    localHashMap.put("&Otilde", Character.valueOf('Õ'));
    localHashMap.put("&Ouml", Character.valueOf('Ö'));
    localHashMap.put("&times", Character.valueOf('×'));
    localHashMap.put("&Oslash", Character.valueOf('Ø'));
    localHashMap.put("&Ugrave", Character.valueOf('Ù'));
    localHashMap.put("&Uacute", Character.valueOf('Ú'));
    localHashMap.put("&Ucirc", Character.valueOf('Û'));
    localHashMap.put("&Uuml", Character.valueOf('Ü'));
    localHashMap.put("&Yacute", Character.valueOf('Ý'));
    localHashMap.put("&THORN", Character.valueOf('Þ'));
    localHashMap.put("&szlig", Character.valueOf('ß'));
    localHashMap.put("&agrave", Character.valueOf('à'));
    localHashMap.put("&aacute", Character.valueOf('á'));
    localHashMap.put("&acirc", Character.valueOf('â'));
    localHashMap.put("&atilde", Character.valueOf('ã'));
    localHashMap.put("&auml", Character.valueOf('ä'));
    localHashMap.put("&aring", Character.valueOf('å'));
    localHashMap.put("&aelig", Character.valueOf('æ'));
    localHashMap.put("&ccedil", Character.valueOf('ç'));
    localHashMap.put("&egrave", Character.valueOf('è'));
    localHashMap.put("&eacute", Character.valueOf('é'));
    localHashMap.put("&ecirc", Character.valueOf('ê'));
    localHashMap.put("&euml", Character.valueOf('ë'));
    localHashMap.put("&igrave", Character.valueOf('ì'));
    localHashMap.put("&iacute", Character.valueOf('í'));
    localHashMap.put("&icirc", Character.valueOf('î'));
    localHashMap.put("&iuml", Character.valueOf('ï'));
    localHashMap.put("&eth", Character.valueOf('ð'));
    localHashMap.put("&ntilde", Character.valueOf('ñ'));
    localHashMap.put("&ograve", Character.valueOf('ò'));
    localHashMap.put("&oacute", Character.valueOf('ó'));
    localHashMap.put("&ocirc", Character.valueOf('ô'));
    localHashMap.put("&otilde", Character.valueOf('õ'));
    localHashMap.put("&ouml", Character.valueOf('ö'));
    localHashMap.put("&divide", Character.valueOf('÷'));
    localHashMap.put("&oslash", Character.valueOf('ø'));
    localHashMap.put("&ugrave", Character.valueOf('ù'));
    localHashMap.put("&uacute", Character.valueOf('ú'));
    localHashMap.put("&ucirc", Character.valueOf('û'));
    localHashMap.put("&uuml", Character.valueOf('ü'));
    localHashMap.put("&yacute", Character.valueOf('ý'));
    localHashMap.put("&thorn", Character.valueOf('þ'));
    localHashMap.put("&yuml", Character.valueOf('ÿ'));
    localHashMap.put("&fnof", Character.valueOf('ƒ'));
    localHashMap.put("&Alpha", Character.valueOf('Α'));
    localHashMap.put("&Beta", Character.valueOf('Β'));
    localHashMap.put("&Gamma", Character.valueOf('Γ'));
    localHashMap.put("&Delta", Character.valueOf('Δ'));
    localHashMap.put("&Epsilon", Character.valueOf('Ε'));
    localHashMap.put("&Zeta", Character.valueOf('Ζ'));
    localHashMap.put("&Eta", Character.valueOf('Η'));
    localHashMap.put("&Theta", Character.valueOf('Θ'));
    localHashMap.put("&Iota", Character.valueOf('Ι'));
    localHashMap.put("&Kappa", Character.valueOf('Κ'));
    localHashMap.put("&Lambda", Character.valueOf('Λ'));
    localHashMap.put("&Mu", Character.valueOf('Μ'));
    localHashMap.put("&Nu", Character.valueOf('Ν'));
    localHashMap.put("&Xi", Character.valueOf('Ξ'));
    localHashMap.put("&Omicron", Character.valueOf('Ο'));
    localHashMap.put("&Pi", Character.valueOf('Π'));
    localHashMap.put("&Rho", Character.valueOf('Ρ'));
    localHashMap.put("&Sigma", Character.valueOf('Σ'));
    localHashMap.put("&Tau", Character.valueOf('Τ'));
    localHashMap.put("&Upsilon", Character.valueOf('Υ'));
    localHashMap.put("&Phi", Character.valueOf('Φ'));
    localHashMap.put("&Chi", Character.valueOf('Χ'));
    localHashMap.put("&Psi", Character.valueOf('Ψ'));
    localHashMap.put("&Omega", Character.valueOf('Ω'));
    localHashMap.put("&alpha", Character.valueOf('α'));
    localHashMap.put("&beta", Character.valueOf('β'));
    localHashMap.put("&gamma", Character.valueOf('γ'));
    localHashMap.put("&delta", Character.valueOf('δ'));
    localHashMap.put("&epsilon", Character.valueOf('ε'));
    localHashMap.put("&zeta", Character.valueOf('ζ'));
    localHashMap.put("&eta", Character.valueOf('η'));
    localHashMap.put("&theta", Character.valueOf('θ'));
    localHashMap.put("&iota", Character.valueOf('ι'));
    localHashMap.put("&kappa", Character.valueOf('κ'));
    localHashMap.put("&lambda", Character.valueOf('λ'));
    localHashMap.put("&mu", Character.valueOf('μ'));
    localHashMap.put("&nu", Character.valueOf('ν'));
    localHashMap.put("&xi", Character.valueOf('ξ'));
    localHashMap.put("&omicron", Character.valueOf('ο'));
    localHashMap.put("&pi", Character.valueOf('π'));
    localHashMap.put("&rho", Character.valueOf('ρ'));
    localHashMap.put("&sigmaf", Character.valueOf('ς'));
    localHashMap.put("&sigma", Character.valueOf('σ'));
    localHashMap.put("&tau", Character.valueOf('τ'));
    localHashMap.put("&upsilon", Character.valueOf('υ'));
    localHashMap.put("&phi", Character.valueOf('φ'));
    localHashMap.put("&chi", Character.valueOf('χ'));
    localHashMap.put("&psi", Character.valueOf('ψ'));
    localHashMap.put("&omega", Character.valueOf('ω'));
    localHashMap.put("&thetasym", Character.valueOf('ϑ'));
    localHashMap.put("&upsih", Character.valueOf('ϒ'));
    localHashMap.put("&piv", Character.valueOf('ϖ'));
    localHashMap.put("&bull", Character.valueOf('•'));
    localHashMap.put("&hellip", Character.valueOf('…'));
    localHashMap.put("&prime", Character.valueOf('′'));
    localHashMap.put("&Prime", Character.valueOf('″'));
    localHashMap.put("&oline", Character.valueOf('‾'));
    localHashMap.put("&frasl", Character.valueOf('⁄'));
    localHashMap.put("&weierp", Character.valueOf('℘'));
    localHashMap.put("&image", Character.valueOf('ℑ'));
    localHashMap.put("&real", Character.valueOf('ℜ'));
    localHashMap.put("&trade", Character.valueOf('™'));
    localHashMap.put("&alefsym", Character.valueOf('ℵ'));
    localHashMap.put("&larr", Character.valueOf('←'));
    localHashMap.put("&uarr", Character.valueOf('↑'));
    localHashMap.put("&rarr", Character.valueOf('→'));
    localHashMap.put("&darr", Character.valueOf('↓'));
    localHashMap.put("&harr", Character.valueOf('↔'));
    localHashMap.put("&crarr", Character.valueOf('↵'));
    localHashMap.put("&lArr", Character.valueOf('⇐'));
    localHashMap.put("&uArr", Character.valueOf('⇑'));
    localHashMap.put("&rArr", Character.valueOf('⇒'));
    localHashMap.put("&dArr", Character.valueOf('⇓'));
    localHashMap.put("&hArr", Character.valueOf('⇔'));
    localHashMap.put("&forall", Character.valueOf('∀'));
    localHashMap.put("&part", Character.valueOf('∂'));
    localHashMap.put("&exist", Character.valueOf('∃'));
    localHashMap.put("&empty", Character.valueOf('∅'));
    localHashMap.put("&nabla", Character.valueOf('∇'));
    localHashMap.put("&isin", Character.valueOf('∈'));
    localHashMap.put("&notin", Character.valueOf('∉'));
    localHashMap.put("&ni", Character.valueOf('∋'));
    localHashMap.put("&prod", Character.valueOf('∏'));
    localHashMap.put("&sum", Character.valueOf('∑'));
    localHashMap.put("&minus", Character.valueOf('−'));
    localHashMap.put("&lowast", Character.valueOf('∗'));
    localHashMap.put("&radic", Character.valueOf('√'));
    localHashMap.put("&prop", Character.valueOf('∝'));
    localHashMap.put("&infin", Character.valueOf('∞'));
    localHashMap.put("&ang", Character.valueOf('∠'));
    localHashMap.put("&and", Character.valueOf('∧'));
    localHashMap.put("&or", Character.valueOf('∨'));
    localHashMap.put("&cap", Character.valueOf('∩'));
    localHashMap.put("&cup", Character.valueOf('∪'));
    localHashMap.put("&int", Character.valueOf('∫'));
    localHashMap.put("&there4", Character.valueOf('∴'));
    localHashMap.put("&sim", Character.valueOf('∼'));
    localHashMap.put("&cong", Character.valueOf('≅'));
    localHashMap.put("&asymp", Character.valueOf('≈'));
    localHashMap.put("&ne", Character.valueOf('≠'));
    localHashMap.put("&equiv", Character.valueOf('≡'));
    localHashMap.put("&le", Character.valueOf('≤'));
    localHashMap.put("&ge", Character.valueOf('≥'));
    localHashMap.put("&sub", Character.valueOf('⊂'));
    localHashMap.put("&sup", Character.valueOf('⊃'));
    localHashMap.put("&nsub", Character.valueOf('⊄'));
    localHashMap.put("&sube", Character.valueOf('⊆'));
    localHashMap.put("&supe", Character.valueOf('⊇'));
    localHashMap.put("&oplus", Character.valueOf('⊕'));
    localHashMap.put("&otimes", Character.valueOf('⊗'));
    localHashMap.put("&perp", Character.valueOf('⊥'));
    localHashMap.put("&sdot", Character.valueOf('⋅'));
    localHashMap.put("&lceil", Character.valueOf('⌈'));
    localHashMap.put("&rceil", Character.valueOf('⌉'));
    localHashMap.put("&lfloor", Character.valueOf('⌊'));
    localHashMap.put("&rfloor", Character.valueOf('⌋'));
    localHashMap.put("&lang", Character.valueOf('〈'));
    localHashMap.put("&rang", Character.valueOf('〉'));
    localHashMap.put("&loz", Character.valueOf('◊'));
    localHashMap.put("&spades", Character.valueOf('♠'));
    localHashMap.put("&clubs", Character.valueOf('♣'));
    localHashMap.put("&hearts", Character.valueOf('♥'));
    localHashMap.put("&diams", Character.valueOf('♦'));
    localHashMap.put("&quot", Character.valueOf('"'));
    localHashMap.put("&amp", Character.valueOf('&'));
    localHashMap.put("&lt", Character.valueOf('<'));
    localHashMap.put("&gt", Character.valueOf('>'));
    localHashMap.put("&apos", Character.valueOf('\''));
    localHashMap.put("&OElig", Character.valueOf('Œ'));
    localHashMap.put("&oelig", Character.valueOf('œ'));
    localHashMap.put("&Scaron", Character.valueOf('Š'));
    localHashMap.put("&scaron", Character.valueOf('š'));
    localHashMap.put("&Yuml", Character.valueOf('Ÿ'));
    localHashMap.put("&circ", Character.valueOf('ˆ'));
    localHashMap.put("&tilde", Character.valueOf('˜'));
    localHashMap.put("&ensp", Character.valueOf(' '));
    localHashMap.put("&emsp", Character.valueOf(' '));
    localHashMap.put("&thinsp", Character.valueOf(' '));
    localHashMap.put("&zwnj", Character.valueOf('‌'));
    localHashMap.put("&zwj", Character.valueOf('‍'));
    localHashMap.put("&lrm", Character.valueOf('‎'));
    localHashMap.put("&rlm", Character.valueOf('‏'));
    localHashMap.put("&ndash", Character.valueOf('–'));
    localHashMap.put("&mdash", Character.valueOf('—'));
    localHashMap.put("&lsquo", Character.valueOf('‘'));
    localHashMap.put("&rsquo", Character.valueOf('’'));
    localHashMap.put("&sbquo", Character.valueOf('‚'));
    localHashMap.put("&ldquo", Character.valueOf('“'));
    localHashMap.put("&rdquo", Character.valueOf('”'));
    localHashMap.put("&bdquo", Character.valueOf('„'));
    localHashMap.put("&dagger", Character.valueOf('†'));
    localHashMap.put("&Dagger", Character.valueOf('‡'));
    localHashMap.put("&permil", Character.valueOf('‰'));
    localHashMap.put("&lsaquo", Character.valueOf('‹'));
    localHashMap.put("&rsaquo", Character.valueOf('›'));
    localHashMap.put("&euro", Character.valueOf('€'));
    e = Collections.unmodifiableMap(localHashMap);
    f = f.a('A', 'F').a(f.a('a', 'f'));
    g = new bo(new bn().a('<', "&lt;").a('>', "&gt;").a());
    h = Pattern.compile("</?[a-zA-Z][^>]*>");
    i = Pattern.compile("&#?[a-zA-Z0-9]{1,8};");
    HashSet localHashSet = new HashSet();
    localHashSet.add(Character.UnicodeBlock.HANGUL_JAMO);
    localHashSet.add(Character.UnicodeBlock.CJK_RADICALS_SUPPLEMENT);
    localHashSet.add(Character.UnicodeBlock.KANGXI_RADICALS);
    localHashSet.add(Character.UnicodeBlock.CJK_SYMBOLS_AND_PUNCTUATION);
    localHashSet.add(Character.UnicodeBlock.HIRAGANA);
    localHashSet.add(Character.UnicodeBlock.KATAKANA);
    localHashSet.add(Character.UnicodeBlock.BOPOMOFO);
    localHashSet.add(Character.UnicodeBlock.HANGUL_COMPATIBILITY_JAMO);
    localHashSet.add(Character.UnicodeBlock.KANBUN);
    localHashSet.add(Character.UnicodeBlock.BOPOMOFO_EXTENDED);
    localHashSet.add(Character.UnicodeBlock.KATAKANA_PHONETIC_EXTENSIONS);
    localHashSet.add(Character.UnicodeBlock.ENCLOSED_CJK_LETTERS_AND_MONTHS);
    localHashSet.add(Character.UnicodeBlock.CJK_COMPATIBILITY);
    localHashSet.add(Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_A);
    localHashSet.add(Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS);
    localHashSet.add(Character.UnicodeBlock.HANGUL_SYLLABLES);
    localHashSet.add(Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS);
    localHashSet.add(Character.UnicodeBlock.CJK_COMPATIBILITY_FORMS);
    localHashSet.add(Character.UnicodeBlock.HALFWIDTH_AND_FULLWIDTH_FORMS);
    localHashSet.add(Character.UnicodeBlock.CJK_UNIFIED_IDEOGRAPHS_EXTENSION_B);
    localHashSet.add(Character.UnicodeBlock.CJK_COMPATIBILITY_IDEOGRAPHS_SUPPLEMENT);
    j = Collections.unmodifiableSet(localHashSet);
    k = "0123456789abcdef".toCharArray();
    l = "01234567".toCharArray();
    m = new bq().a(173).a(1536, 1539).a(1757).a(1807).a(6068, 6069).a(8203, 8207).a(8234, 8238).a(8288, 8292).a(8298, 8303).a(65279).a(65529, 65531).a(119155, 119162).a(917505).a(917536, 917631).a(0).a(10).a(13).a(8232, 8233).a(133).a(Character.codePointAt("'", 0)).a(Character.codePointAt("\"", 0)).a(Character.codePointAt("&", 0)).a(Character.codePointAt("<", 0)).a(Character.codePointAt(">", 0)).a(Character.codePointAt("=", 0)).a(Character.codePointAt("\\", 0)).a();
    bp localbp1 = new bq().a(Character.codePointAt("\"", 0)).a(Character.codePointAt("\\", 0)).a(0, 31).a();
    bp localbp2 = m;
    int i2;
    -1.<init>();
    int i1;
  }

  public static boolean a(String paramString)
  {
    return (paramString == null) || (f.o.b(paramString));
  }
}

/* Location:           classes_dex2jar.jar
 * Qualified Name:     com.google.a.a.bl
 * JD-Core Version:    0.6.2
 */